//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SunsetHotelSystem.Dominio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSH_Tipo_Habitacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TSH_Tipo_Habitacion()
        {
            this.TSH_Caracteristica_habitacion = new HashSet<TSH_Caracteristica_habitacion>();
            this.TSH_Habitacion = new HashSet<TSH_Habitacion>();
        }
    
        public int TN_Identificador_TSH_Tipo_Habitacion { get; set; }
        public double TN_Tarifa_TSH_Tipo_Habitacion { get; set; }
        public string TC_Titulo_TSH_Tipo_Habitacion { get; set; }
        public int TN_Cantidad_Personas_TSH_Tipo_Habitacion { get; set; }
        public string TC_Descripcion_TSH_Tipo_Habitacion { get; set; }
        public Nullable<System.Guid> TN_Id_Imagen_TSH_Tipo_Habitacion { get; set; }
        public byte[] TI_Imagen_TSH_Tipo_Habitacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSH_Caracteristica_habitacion> TSH_Caracteristica_habitacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSH_Habitacion> TSH_Habitacion { get; set; }
    }
}
