//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SunsetHotelSystem.Dominio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSH_Administrador
    {
        public string TC_Correo_TSH_Administrador { get; set; }
        public string TC_contrasenia_TSH_Administrador { get; set; }
    }
}
