//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SunsetHotelSystem.Dominio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSH_Pagina
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TSH_Pagina()
        {
            this.TSH_Pag_Facilidades = new HashSet<TSH_Pag_Facilidades>();
            this.TSH_SobreN_Galeria = new HashSet<TSH_SobreN_Galeria>();
        }
    
        public int TN_Identificador_TSH_Pagina { get; set; }
        public string TC_Descripcion_TSH_Pagina { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSH_Pag_Facilidades> TSH_Pag_Facilidades { get; set; }
        public virtual TSH_Pag_Home TSH_Pag_Home { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSH_SobreN_Galeria> TSH_SobreN_Galeria { get; set; }
    }
}
