//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SunsetHotelSystem.Dominio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSH_Publicidad
    {
        public int TN_Identificador_TSH_Publicidad { get; set; }
        public System.Guid TN_Id_Imagen_TSH_Publicidad { get; set; }
        public byte[] TI_Imagen_TSH_Publicidad { get; set; }
        public string TC_Direccion_Pagina_TSH_Publicidad { get; set; }
    }
}
